import fs from 'fs';
import path from 'path';
import _ from 'lodash';

const DIR_PATH = path.resolve (__dirname, './needTranslateFiles/');
const FORMATED_DIR_PATH = path.resolve (__dirname, './formatedFiles/');
const TEMP_LINE = 'Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{{text}}';
// const dirPath = path.resolve (__dirname, './needTranslateFiles/');
// const formatDirPath = path.resolve (__dirname, './formatedFiles/');

const dirNameArr = fs.readdirSync (path.resolve (DIR_PATH));

_.each (dirNameArr, fileName => {
  const fileDoc = fs.readFileSync (path.resolve (DIR_PATH, fileName), {
    encoding: 'utf8',
  });

  const fileDocLines = fileDoc.split ('\n');

  const dialogs = _.map (fileDocLines, text => {
    return TEMP_LINE.replace ('{{text}}', text);
  });
  const fileDocDetail = `
    [Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[Aegisub Project Garbage]
Active Line: 1

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
${dialogs.join ('\n')}
  `;

  fs.writeFileSync (
    path.resolve (FORMATED_DIR_PATH, fileName.split ('.')[0] + '.ass'),
    fileDocDetail
  );
});

console.log ('Success!');
